<?php

function mls_plugin_get_current_language() {
	
    if (!get_option('mls_plugin_style_proplanghide')) {
    $prpdtselected_page_id = get_option('mls_plugin_property_detail_page_id', '');
    $prpdetailpage_id = $prpdtselected_page_id ? $prpdtselected_page_id : 7865;

    if (is_page($prpdetailpage_id)) {
        $language_code = get_option('mls_temp_language_code', '1');
    } else {
        $language_code = get_option('mls_plugin_prop_language', '1');
    }
} else {
    $language_code = get_option('mls_temp_language_code', '1');
}
	
    $languages_map = [
        '1' => 'en', '2' => 'es', '3' => 'de', '4' => 'fr', '5' => 'nl', 
        '6' => 'da', '7' => 'ru', '8' => 'sv', '9' => 'pl', '10' => 'no', 
        '11' => 'tr', '13' => 'fi', '14' => 'hu'
    ];
    return $languages_map[$language_code] ?? 'en'; // Fallback to English if not found
}



function mls_plugin_get_translations() {
    return [
        'en' => [
        
        'labels' => [
            'searchtitle' => 'Discover your ideal home today!',
            'sales' => 'Sales',
			'long_rentals' => 'Rentals',
			'short_rentals' => 'Holiday',
			'new_development' => 'New development',
			'area' => 'Location:',
			'child_area' => 'Sub-Area:',
			'no_area' => 'No locations available',
            'property_type' => 'Property Type:',
			'no_property_type' => 'No property types available',
            'reference_id' => 'Reference ID:',
            'beds' => 'Beds:',
            'baths' => 'Baths:',
            'min_price' => 'Min Price:',
            'max_price' => 'Max Price:',
			'price' => 'Price:',
			'price_selector' => 'Price selector',
			'price_range' => ' Price Range:',
			'sort_by' => 'Sort by:',
			'for_rent' => 'For Rent',
			'for_sale' => 'For Sale',
			'featured' => 'Featured',
			'tour_type' => 'Tour Type:',
			'feature_search_type' => 'Features Search Type',
			'tour_type_desc' => '"If you are unable to visit the property in person, we can visit for you and connect via whatsapp video to give you a tour."',
        ],
        'placeholders' => [
            'search_reference_id' => 'Search by Reference ID',
			'search_area' => 'Select location',
			'all_child_area' => 'All locations',
			'search_property_type' => 'Select Property types',
			'search_pricerange' => 'Please select a price range',
			'search_pricerange_select' => 'Select a price range',
			'search_pricerange_upto' => 'Up to ',
			'search_pricerange_startsfrom' => 'Starts from ',
			'search_pricerange_to' => ' to ',
			'search_select_dropdown_search' => 'Search',
			'search_select_dropdown_clearall' => 'Clear all',
			'search_select_dropdown_selectall' => 'Select all',
			'your_phone' => 'Your Phone',
			'your_email' => 'Your Email',
			'your_name' => 'Your Name',
			'buyer' => 'Buyer',
			'agent' => 'Agent',
			'person' => 'In Person',
			'video' => 'Video',
			'comment' => "I'm interested in ",
        ],
        'buttons' => [
            'search_properties' => 'Search Properties',
			'search_features' => 'Additional Features',
			'submit_request' => 'Submit Request',
			'view_more' => 'View More',
			'reset' => 'Reset',
			'done' => 'Done',
			'additionalfeatures' => 'Additional Features',
			'back_previous' => 'Back to previous page',
			'back_home' => 'Back to Home',
			'virtual_tour' => 'Virtual Tour',
			'video_tour' => 'Video Tour',
			'book_viewing' => 'Book a Viewing',
        ],
        'options' => [
                'any' => 'Any',
                'sort_lowest_price' => 'Price (Lowest First)',
                'sort_highest_price' => 'Price (Highest First)',
                'sort_location' => 'Location',
                'sort_most_recent' => 'Most Recent First',
                'sort_oldest' => 'Oldest First',
			'musthavefeatures1' => 'Match Any Feature (Partial) – Show properties with any of the selected features',
			'musthavefeatures2' => 'Match All Features (Exact) – Show only properties with all selected features', 
        ],
		'error' => [
        'prpreferr' => 'Add Reference attributte & Property ID to show the Properties',
        'mls_nosearchresult' => 'No search results found. Please try searching again.',
        'mls_sessionexpired' => 'Session expired. Please try searching again.',
		'mls_no_properties_found' => 'No properties found.',
		'mls_propertdetail_invalid_found' => 'Invalid property information.',
		'mls_propertdetail_not_found' => 'Property not found.',
		'mls_propertdetail_no_features' => 'No Features Available.',
		'mls_propertdetail_no_amenities' => 'No amenities available',
		'mls_propertdetail_form_name' => 'Please enter your name.',
		'mls_propertdetail_form_email' => 'Please enter your email.',
			'mls_propertdetail_form_valid_email' => 'Please enter a valid email.',
			'mls_propertdetail_form_phone_number' => 'Please enter your phone number.',
			'mls_propertdetail_form_valid_phone_number' => 'Please enter a valid phone number.',
			'mls_propertdetail_form_scheduledate' => 'Please select a schedule date.',
			'mls_propertdetail_form_submitting' => 'Submitting...',
			'mls_propertdetail_form_submitrequest' => 'Submit Request',
			'mls_propertdetail_form_submiterror' => 'There was an issue submitting the form. Please try again.',
			'mls_propertdetail_form_submitsuccess' => 'Thank you! Your request has been submitted, and an email has been sent.',
			'mls_propertdetail_form_submitrequiredmissing' => 'Required fields are missing.',
    	],
		'general' => [
        'in' => 'in',
		'month' => 'Month',
		'share' => 'Share this:',
		'features' => 'Features',
		'amenities' => 'Amenities',
		'description' => 'Description',
		'additionalfeatures' => 'Additional Features',
		'selectoption' => 'Select Options',
		'properties_found' => ' properties found.',
    	],
		'specification' => [
        'bedrooms' => 'Bedrooms',
		'bathrooms' => 'Bathrooms',
		'built' => 'Built Area',
		'garden' => 'Garden Plot',
		'terrace' => 'Terrace',
    	],
		'prp_highlights' => [
        'property_highlights' => 'Property Highlights',
		'referenceid' => 'Reference ID',
		'price' => 'Price',
		'location' => 'Location',
		'area' => 'Area',
		'country' => 'Country',
		'property_type' => 'Property type',
		'garbage_fees' => 'Garbage fees/year',
		'ibi_fees' => 'IBI Fees',
    	],
		'prp_map' => [
        'property_location' => 'Property Location (Approximate)',
		'property_location_descp' => 'For privacy reasons, the map displays an approximate location of the property. Please contact us for precise details or to arrange a viewing.',
		
    	],
			
			
    ],
	'es' => [
    'labels' => [
        'searchtitle' => '¡Descubre tu hogar ideal hoy!',
        'sales' => 'Venta',
        'long_rentals' => 'Alquileres',
        'short_rentals' => 'Vacacional',
        'new_development' => 'Nueva promoción',
        'area' => 'Ubicación:',
        'child_area' => 'Subárea:',
        'no_area' => 'No hay ubicaciones disponibles',
        'property_type' => 'Tipo de propiedad:',
        'no_property_type' => 'No hay tipos de propiedad disponibles',
        'reference_id' => 'Referencia:',
        'beds' => 'Dormitorios:',
        'baths' => 'Baños:',
        'min_price' => 'Precio mínimo:',
        'max_price' => 'Precio máximo:',
        'price' => 'Precio:',
        'price_selector' => 'Selector de precio',
        'price_range' => 'Rango de precios:',
        'sort_by' => 'Ordenar por:',
        'for_rent' => 'En alquiler',
        'for_sale' => 'En venta',
        'featured' => 'Destacado',
        'tour_type' => 'Tipo de visita:',
        'feature_search_type' => 'Tipo de búsqueda por características',
        'tour_type_desc' => '“Si no puedes visitar la propiedad en persona, podemos hacerlo por ti y conectarte por video de WhatsApp para una visita.”',
    ],
    'placeholders' => [
        'search_reference_id' => 'Buscar por referencia',
        'search_area' => 'Seleccionar ubicación',
        'all_child_area' => 'Todas las ubicaciones',
        'search_property_type' => 'Seleccionar tipos de propiedad',
        'search_pricerange' => 'Seleccione un rango de precios',
        'search_pricerange_select' => 'Seleccionar un rango de precios',
        'search_pricerange_upto' => 'Hasta ',
        'search_pricerange_startsfrom' => 'Desde ',
        'search_pricerange_to' => ' a ',
        'search_select_dropdown_search' => 'Buscar',
        'search_select_dropdown_clearall' => 'Borrar todo',
        'search_select_dropdown_selectall' => 'Seleccionar todo',
        'your_phone' => 'Tu teléfono',
        'your_email' => 'Tu correo electrónico',
        'your_name' => 'Tu nombre',
        'buyer' => 'Comprador',
        'agent' => 'Agente',
        'person' => 'En persona',
        'video' => 'Video',
        'comment' => "Estoy interesado en ",
    ],
    'buttons' => [
        'search_properties' => 'Buscar propiedades',
        'search_features' => 'Características adicionales',
        'submit_request' => 'Enviar solicitud',
        'view_more' => 'Ver más',
        'reset' => 'Restablecer',
        'done' => 'Hecho',
        'additionalfeatures' => 'Características adicionales',
        'back_previous' => 'Volver a la página anterior',
        'back_home' => 'Volver al inicio',
        'virtual_tour' => 'Visita virtual',
        'video_tour' => 'Tour en video',
        'book_viewing' => 'Reservar visita',
    ],
    'options' => [
        'any' => 'Cualquiera',
        'sort_lowest_price' => 'Precio (más bajo primero)',
        'sort_highest_price' => 'Precio (más alto primero)',
        'sort_location' => 'Ubicación',
        'sort_most_recent' => 'Más reciente primero',
        'sort_oldest' => 'Más antiguo primero',
        'musthavefeatures1' => 'Coincidir con cualquier característica – Mostrar propiedades con cualquiera de las características seleccionadas',
        'musthavefeatures2' => 'Coincidir con todas las características – Mostrar solo propiedades con todas las características seleccionadas',
    ],
    'error' => [
        'prpreferr' => 'Agregue el atributo de referencia y el ID de propiedad para mostrar las propiedades',
        'mls_nosearchresult' => 'No se encontraron resultados. Intente nuevamente.',
        'mls_sessionexpired' => 'Sesión expirada. Vuelva a buscar.',
        'mls_no_properties_found' => 'No se encontraron propiedades.',
        'mls_propertdetail_invalid_found' => 'Información de propiedad no válida.',
        'mls_propertdetail_not_found' => 'Propiedad no encontrada.',
        'mls_propertdetail_no_features' => 'Sin características disponibles.',
        'mls_propertdetail_no_amenities' => 'No hay servicios disponibles.',
        'mls_propertdetail_form_name' => 'Por favor, ingrese su nombre.',
        'mls_propertdetail_form_email' => 'Por favor, ingrese su correo electrónico.',
        'mls_propertdetail_form_valid_email' => 'Ingrese un correo válido.',
        'mls_propertdetail_form_phone_number' => 'Ingrese su número de teléfono.',
        'mls_propertdetail_form_valid_phone_number' => 'Ingrese un número válido.',
        'mls_propertdetail_form_scheduledate' => 'Seleccione una fecha para la cita.',
        'mls_propertdetail_form_submitting' => 'Enviando...',
        'mls_propertdetail_form_submitrequest' => 'Enviar solicitud',
        'mls_propertdetail_form_submiterror' => 'Hubo un error al enviar el formulario. Inténtelo de nuevo.',
        'mls_propertdetail_form_submitsuccess' => '¡Gracias! Su solicitud ha sido enviada y se ha enviado un correo electrónico.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Faltan campos obligatorios.',
    ],
    'general' => [
        'in' => 'en',
        'month' => 'Mes',
        'share' => 'Compartir:',
        'features' => 'Características',
        'amenities' => 'Servicios',
        'description' => 'Descripción',
        'additionalfeatures' => 'Características adicionales',
        'selectoption' => 'Seleccionar opciones',
        'properties_found' => ' propiedades encontradas.',
    ],
    'specification' => [
        'bedrooms' => 'Dormitorios',
        'bathrooms' => 'Baños',
        'built' => 'Área construida',
        'garden' => 'Parcela / Jardín',
        'terrace' => 'Terraza',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Aspectos destacados de la propiedad',
        'referenceid' => 'Referencia',
        'price' => 'Precio',
        'location' => 'Ubicación',
        'area' => 'Zona',
        'country' => 'País',
        'property_type' => 'Tipo de propiedad',
        'garbage_fees' => 'Tasa de basura/año',
        'ibi_fees' => 'Gastos IBI',
    ],
    'prp_map' => [
        'property_location' => 'Ubicación de la propiedad (aproximada)',
        'property_location_descp' => 'Por razones de privacidad, el mapa muestra una ubicación aproximada. Contáctenos para más detalles o concertar una visita.',
    ],
],

'de' => [
    'labels' => [
        'searchtitle' => 'Entdecken Sie noch heute Ihr Traumhaus!',
        'sales' => 'Verkauf',
        'long_rentals' => 'Langzeitmiete',
        'short_rentals' => 'Ferienwohnung',
        'new_development' => 'Neubau',
        'area' => 'Gebiet:',
        'no_area' => 'Keine Standorte verfügbar',
        'property_type' => 'Immobilientyp:',
        'no_property_type' => 'Keine Immobilientypen verfügbar',
        'reference_id' => 'Referenznummer:',
        'beds' => 'Schlafzimmer:',
        'baths' => 'Badezimmer:',
        'min_price' => 'Mindestpreis:',
        'max_price' => 'Höchstpreis:',
        'price' => 'Preis:',
        'price_selector' => 'Preisauswahl',
        'price_range' => 'Preisspanne:',
        'sort_by' => 'Sortieren nach:',
        'for_rent' => 'Zu vermieten',
        'for_sale' => 'Zu verkaufen',
        'featured' => 'Hervorgehoben',
        'tour_type' => 'Besichtigungstyp:',
        'feature_search_type' => 'Merkmals-Suchtyp',
        'tour_type_desc' => '"Falls Sie die Immobilie nicht persönlich besichtigen können, können wir dies für Sie tun und Ihnen per WhatsApp-Video eine Besichtigung ermöglichen."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Nach Referenznummer suchen',
        'search_area' => 'Standort auswählen',
        'search_property_type' => 'Immobilientypen auswählen',
		'search_pricerange' => 'Bitte wählen Sie eine Preisspanne',
        'search_pricerange_select' => 'Wählen Sie eine Preisspanne',
        'search_pricerange_upto' => 'Bis ',
        'search_pricerange_startsfrom' => 'Ab ',
        'search_pricerange_to' => ' bis ',
        'search_select_dropdown_search' => 'Suchen',
        'search_select_dropdown_clearall' => 'Alles löschen',
        'search_select_dropdown_selectall' => 'Alles auswählen',
        'your_phone' => 'Ihre Telefonnummer',
        'your_email' => 'Ihre E-Mail',
        'your_name' => 'Ihr Name',
        'buyer' => 'Käufer',
        'agent' => 'Makler',
        'person' => 'Persönlich',
        'video' => 'Video',
        'comment' => "Ich interessiere mich für ",
    ],
    'buttons' => [
        'search_properties' => 'Immobilien suchen',
        'search_features' => 'Zusätzliche Merkmale',
        'submit_request' => 'Anfrage senden',
        'view_more' => 'Mehr anzeigen',
        'reset' => 'Zurücksetzen',
        'done' => 'Fertig',
        'additionalfeatures' => 'Zusätzliche Merkmale',
        'back_previous' => 'Zurück zur vorherigen Seite',
        'back_home' => 'Zurück zur Startseite',
        'virtual_tour' => 'Virtuelle Besichtigung',
        'video_tour' => 'Video-Besichtigung',
        'book_viewing' => 'Besichtigung buchen',
    ],
    'options' => [
        'any' => 'Beliebig',
        'sort_lowest_price' => 'Preis (aufsteigend)',
        'sort_highest_price' => 'Preis (absteigend)',
        'sort_location' => 'Standort',
        'sort_most_recent' => 'Neueste zuerst',
        'sort_oldest' => 'Älteste zuerst',
        'musthavefeatures1' => 'Beliebiges Merkmal (teilweise) – Zeigt Immobilien mit mindestens einem der ausgewählten Merkmale',
        'musthavefeatures2' => 'Alle Merkmale (exakt) – Zeigt nur Immobilien mit allen ausgewählten Merkmalen', 
    ],
    'error' => [
        'prpreferr' => 'Fügen Sie das Referenzattribut und die Immobilien-ID hinzu, um die Immobilien anzuzeigen',
        'mls_nosearchresult' => 'Keine Suchergebnisse gefunden. Bitte versuchen Sie es erneut.',
        'mls_sessionexpired' => 'Sitzung abgelaufen. Bitte versuchen Sie es erneut.',
        'mls_no_properties_found' => 'Keine Immobilien gefunden.',
        'mls_propertdetail_invalid_found' => 'Ungültige Immobiliendaten.',
        'mls_propertdetail_not_found' => 'Immobilie nicht gefunden.',
        'mls_propertdetail_no_features' => 'Keine Merkmale verfügbar.',
        'mls_propertdetail_no_amenities' => 'Keine Annehmlichkeiten verfügbar',
        'mls_propertdetail_form_name' => 'Bitte geben Sie Ihren Namen ein.',
        'mls_propertdetail_form_email' => 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
        'mls_propertdetail_form_valid_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
        'mls_propertdetail_form_phone_number' => 'Bitte geben Sie Ihre Telefonnummer ein.',
        'mls_propertdetail_form_valid_phone_number' => 'Bitte geben Sie eine gültige Telefonnummer ein.',
        'mls_propertdetail_form_scheduledate' => 'Bitte wählen Sie ein Datum aus.',
        'mls_propertdetail_form_submitting' => 'Wird gesendet...',
        'mls_propertdetail_form_submitrequest' => 'Anfrage senden',
        'mls_propertdetail_form_submiterror' => 'Beim Senden des Formulars ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
        'mls_propertdetail_form_submitsuccess' => 'Vielen Dank! Ihre Anfrage wurde gesendet und eine E-Mail wurde versandt.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Erforderliche Felder fehlen.',
    ],
    'general' => [
        'in' => 'in',
        'month' => 'Monat',
        'share' => 'Teilen:',
        'features' => 'Merkmale',
        'description' => 'Beschreibung',
        'additionalfeatures' => 'Zusätzliche Merkmale',
    ],
    'specification' => [
        'bedrooms' => 'Schlafzimmer',
        'bathrooms' => 'Badezimmer',
        'built' => 'Wohnfläche',
        'garden' => 'Gartengrundstück',
        'terrace' => 'Terrasse',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Immobilien-Highlights',
        'referenceid' => 'Referenznummer',
        'price' => 'Preis',
        'location' => 'Standort',
        'area' => 'Gebiet',
        'country' => 'Land',
        'property_type' => 'Immobilientyp',
        'garbage_fees' => 'Müllgebühren/Jahr',
        'ibi_fees' => 'Grundsteuer',
    ],
    'prp_map' => [
        'property_location' => 'Standort der Immobilie (ungefähr)',
        'property_location_descp' => 'Aus Datenschutzgründen zeigt die Karte den ungefähren Standort der Immobilie. Bitte kontaktieren Sie uns für genaue Details oder um eine Besichtigung zu vereinbaren.',
    ],
],
		'fr' => [
    'labels' => [
        'searchtitle' => 'Découvrez votre maison idéale dès aujourd\'hui !',
        'sales' => 'Vente',
        'long_rentals' => 'Location longue durée',
        'short_rentals' => 'Location vacances',
        'new_development' => 'Nouveau projet',
        'area' => 'Zone :',
        'no_area' => 'Aucun emplacement disponible',
        'property_type' => 'Type de bien :',
        'no_property_type' => 'Aucun type de bien disponible',
        'reference_id' => 'Référence :',
        'beds' => 'Chambres :',
        'baths' => 'Salles de bain :',
        'min_price' => 'Prix min :',
        'max_price' => 'Prix max :',
        'price' => 'Prix :',
        'price_selector' => 'Sélecteur de prix',
        'price_range' => 'Tranche de prix :',
        'sort_by' => 'Trier par :',
        'for_rent' => 'À louer',
        'for_sale' => 'À vendre',
        'featured' => 'En vedette',
        'tour_type' => 'Type de visite :',
        'feature_search_type' => 'Type de recherche par caractéristiques',
        'tour_type_desc' => '"Si vous ne pouvez pas visiter le bien en personne, nous pouvons le visiter pour vous et vous faire une visite via WhatsApp vidéo."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Rechercher par référence',
        'search_area' => 'Sélectionner un emplacement',
        'search_property_type' => 'Sélectionner les types de biens',
		'search_pricerange' => 'Veuillez sélectionner une gamme de prix',
        'search_pricerange_select' => 'Sélectionnez une gamme de prix',
        'search_pricerange_upto' => 'Jusqu’à ',
        'search_pricerange_startsfrom' => 'À partir de ',
        'search_pricerange_to' => ' à ',
        'search_select_dropdown_search' => 'Rechercher',
        'search_select_dropdown_clearall' => 'Tout effacer',
        'search_select_dropdown_selectall' => 'Tout sélectionner',
        'your_phone' => 'Votre téléphone',
        'your_email' => 'Votre email',
        'your_name' => 'Votre nom',
        'buyer' => 'Acheteur',
        'agent' => 'Agent',
        'person' => 'En personne',
        'video' => 'Vidéo',
        'comment' => "Je suis intéressé par ",
    ],
    'buttons' => [
        'search_properties' => 'Rechercher des biens',
        'search_features' => 'Caractéristiques supplémentaires',
        'submit_request' => 'Soumettre la demande',
        'view_more' => 'Voir plus',
        'reset' => 'Réinitialiser',
        'done' => 'Terminé',
        'additionalfeatures' => 'Caractéristiques supplémentaires',
        'back_previous' => 'Retour à la page précédente',
        'back_home' => 'Retour à l\'accueil',
        'virtual_tour' => 'Visite virtuelle',
        'video_tour' => 'Visite vidéo',
        'book_viewing' => 'Réserver une visite',
    ],
    'options' => [
        'any' => 'Tous',
        'sort_lowest_price' => 'Prix (croissant)',
        'sort_highest_price' => 'Prix (décroissant)',
        'sort_location' => 'Emplacement',
        'sort_most_recent' => 'Plus récent d\'abord',
        'sort_oldest' => 'Plus ancien d\'abord',
        'musthavefeatures1' => 'Correspond à n\'importe quelle caractéristique (partielle) – Affiche les biens avec au moins une des caractéristiques sélectionnées',
        'musthavefeatures2' => 'Correspond à toutes les caractéristiques (exact) – Affiche uniquement les biens avec toutes les caractéristiques sélectionnées', 
    ],
    'error' => [
        'prpreferr' => 'Ajoutez l\'attribut de référence et l\'ID du bien pour afficher les propriétés',
        'mls_nosearchresult' => 'Aucun résultat de recherche trouvé. Veuillez réessayer.',
        'mls_sessionexpired' => 'Session expirée. Veuillez réessayer.',
        'mls_no_properties_found' => 'Aucun bien trouvé.',
        'mls_propertdetail_invalid_found' => 'Informations sur le bien non valides.',
        'mls_propertdetail_not_found' => 'Bien non trouvé.',
        'mls_propertdetail_no_features' => 'Aucune caractéristique disponible.',
        'mls_propertdetail_no_amenities' => 'Aucun équipement disponible',
        'mls_propertdetail_form_name' => 'Veuillez entrer votre nom.',
        'mls_propertdetail_form_email' => 'Veuillez entrer votre email.',
        'mls_propertdetail_form_valid_email' => 'Veuillez entrer un email valide.',
        'mls_propertdetail_form_phone_number' => 'Veuillez entrer votre numéro de téléphone.',
        'mls_propertdetail_form_valid_phone_number' => 'Veuillez entrer un numéro de téléphone valide.',
        'mls_propertdetail_form_scheduledate' => 'Veuillez sélectionner une date.',
        'mls_propertdetail_form_submitting' => 'Envoi en cours...',
        'mls_propertdetail_form_submitrequest' => 'Soumettre la demande',
        'mls_propertdetail_form_submiterror' => 'Un problème est survenu lors de l\'envoi du formulaire. Veuillez réessayer.',
        'mls_propertdetail_form_submitsuccess' => 'Merci ! Votre demande a été soumise et un email a été envoyé.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Des champs obligatoires sont manquants.',
    ],
    'general' => [
        'in' => 'à',
        'month' => 'Mois',
        'share' => 'Partager :',
        'features' => 'Caractéristiques',
        'description' => 'Description',
        'additionalfeatures' => 'Caractéristiques supplémentaires',
    ],
    'specification' => [
        'bedrooms' => 'Chambres',
        'bathrooms' => 'Salles de bain',
        'built' => 'Surface construite',
        'garden' => 'Jardin',
        'terrace' => 'Terrasse',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Points forts du bien',
        'referenceid' => 'Référence',
        'price' => 'Prix',
        'location' => 'Emplacement',
        'area' => 'Zone',
        'country' => 'Pays',
        'property_type' => 'Type de bien',
        'garbage_fees' => 'Frais d\'ordures/an',
        'ibi_fees' => 'Taxe foncière',
    ],
    'prp_map' => [
        'property_location' => 'Emplacement du bien (approximatif)',
        'property_location_descp' => 'Pour des raisons de confidentialité, la carte affiche un emplacement approximatif du bien. Veuillez nous contacter pour des détails précis ou pour organiser une visite.',
    ],
],
		'nl' => [
    'labels' => [
        'searchtitle' => 'Ontdek vandaag nog uw ideale huis!',
        'sales' => 'Verkoop',
        'long_rentals' => 'Huur',
        'short_rentals' => 'Vakantie',
        'new_development' => 'Nieuwbouw',
        'area' => 'Gebied:',
        'no_area' => 'Geen locaties beschikbaar',
        'property_type' => 'Type woning:',
        'no_property_type' => 'Geen woningtypen beschikbaar',
        'reference_id' => 'Referentienummer:',
        'beds' => 'Slaapkamers:',
        'baths' => 'Badkamers:',
        'min_price' => 'Min. prijs:',
        'max_price' => 'Max. prijs:',
        'price' => 'Prijs:',
        'price_selector' => 'Prijsselector',
        'price_range' => 'Prijsbereik:',
        'sort_by' => 'Sorteren op:',
        'for_rent' => 'Te huur',
        'for_sale' => 'Te koop',
        'featured' => 'Uitgelicht',
        'tour_type' => 'Rondleiding type:',
        'feature_search_type' => 'Zoektype kenmerken',
        'tour_type_desc' => '"Als u de woning niet persoonlijk kunt bezoeken, kunnen wij dit voor u doen en u via WhatsApp-video een rondleiding geven."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Zoeken op referentienummer',
        'search_area' => 'Locatie selecteren',
        'search_property_type' => 'Woningtypen selecteren',
		'search_pricerange' => 'Selecteer een prijsklasse',
        'search_pricerange_select' => 'Kies een prijsklasse',
        'search_pricerange_upto' => 'Tot ',
        'search_pricerange_startsfrom' => 'Vanaf ',
        'search_pricerange_to' => ' tot ',
        'search_select_dropdown_search' => 'Zoeken',
        'search_select_dropdown_clearall' => 'Alles wissen',
        'search_select_dropdown_selectall' => 'Alles selecteren',
        'your_phone' => 'Uw telefoonnummer',
        'your_email' => 'Uw e-mail',
        'your_name' => 'Uw naam',
        'buyer' => 'Koper',
        'agent' => 'Makelaar',
        'person' => 'Persoonlijk',
        'video' => 'Video',
        'comment' => "Ik ben geïnteresseerd in ",
    ],
    'buttons' => [
        'search_properties' => 'Zoek woningen',
        'search_features' => 'Extra kenmerken',
        'submit_request' => 'Verzoek indienen',
        'view_more' => 'Meer bekijken',
        'reset' => 'Resetten',
        'done' => 'Klaar',
        'additionalfeatures' => 'Extra kenmerken',
        'back_previous' => 'Terug naar vorige pagina',
        'back_home' => 'Terug naar home',
        'virtual_tour' => 'Virtuele tour',
        'video_tour' => 'Video tour',
        'book_viewing' => 'Rondleiding boeken',
    ],
    'options' => [
        'any' => 'Willekeurig',
        'sort_lowest_price' => 'Prijs (laagste eerst)',
        'sort_highest_price' => 'Prijs (hoogste eerst)',
        'sort_location' => 'Locatie',
        'sort_most_recent' => 'Meest recent eerst',
        'sort_oldest' => 'Oudste eerst',
        'musthavefeatures1' => 'Komt overeen met elk kenmerk (gedeeltelijk) – Toon woningen met een van de geselecteerde kenmerken',
        'musthavefeatures2' => 'Komt overeen met alle kenmerken (exact) – Toon alleen woningen met alle geselecteerde kenmerken', 
    ],
    'error' => [
        'prpreferr' => 'Voeg referentie-attribuut en woning-ID toe om de woningen te tonen',
        'mls_nosearchresult' => 'Geen zoekresultaten gevonden. Probeer het opnieuw.',
        'mls_sessionexpired' => 'Sessie verlopen. Probeer het opnieuw.',
        'mls_no_properties_found' => 'Geen woningen gevonden.',
        'mls_propertdetail_invalid_found' => 'Ongeldige woninginformatie.',
        'mls_propertdetail_not_found' => 'Woning niet gevonden.',
        'mls_propertdetail_no_features' => 'Geen kenmerken beschikbaar.',
        'mls_propertdetail_no_amenities' => 'Geen voorzieningen beschikbaar',
        'mls_propertdetail_form_name' => 'Voer uw naam in.',
        'mls_propertdetail_form_email' => 'Voer uw e-mailadres in.',
        'mls_propertdetail_form_valid_email' => 'Voer een geldig e-mailadres in.',
        'mls_propertdetail_form_phone_number' => 'Voer uw telefoonnummer in.',
        'mls_propertdetail_form_valid_phone_number' => 'Voer een geldig telefoonnummer in.',
        'mls_propertdetail_form_scheduledate' => 'Selecteer een datum.',
        'mls_propertdetail_form_submitting' => 'Verzenden...',
        'mls_propertdetail_form_submitrequest' => 'Verzoek indienen',
        'mls_propertdetail_form_submiterror' => 'Er is een probleem opgetreden bij het verzenden van het formulier. Probeer het opnieuw.',
        'mls_propertdetail_form_submitsuccess' => 'Bedankt! Uw verzoek is ingediend en er is een e-mail verzonden.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Verplichte velden ontbreken.',
    ],
    'general' => [
        'in' => 'in',
        'month' => 'Maand',
        'share' => 'Deel dit:',
        'features' => 'Kenmerken',
        'description' => 'Beschrijving',
        'additionalfeatures' => 'Extra kenmerken',
    ],
    'specification' => [
        'bedrooms' => 'Slaapkamers',
        'bathrooms' => 'Badkamers',
        'built' => 'Woonoppervlakte',
        'garden' => 'Tuin',
        'terrace' => 'Terras',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Woning hoogtepunten',
        'referenceid' => 'Referentienummer',
        'price' => 'Prijs',
        'location' => 'Locatie',
        'area' => 'Gebied',
        'country' => 'Land',
        'property_type' => 'Woningtype',
        'garbage_fees' => 'Afvalstoffenheffing/jaar',
        'ibi_fees' => 'Onroerendezaakbelasting',
    ],
    'prp_map' => [
        'property_location' => 'Woninglocatie (benadering)',
        'property_location_descp' => 'Om privacyredenen toont de kaart een benaderde locatie van de woning. Neem contact met ons op voor exacte details of om een bezichtiging te plannen.',
    ],
],
		'ru' => [
    'labels' => [
        'searchtitle' => 'Найдите свой идеальный дом сегодня!',
        'sales' => 'Продажа',
        'long_rentals' => 'Аренда',
        'short_rentals' => 'Отпуск',
        'new_development' => 'Новостройки',
        'area' => 'Район:',
        'no_area' => 'Нет доступных локаций',
        'property_type' => 'Тип недвижимости:',
        'no_property_type' => 'Нет доступных типов недвижимости',
        'reference_id' => 'Референс-номер:',
        'beds' => 'Спальни:',
        'baths' => 'Ванные комнаты:',
        'min_price' => 'Мин. цена:',
        'max_price' => 'Макс. цена:',
        'price' => 'Цена:',
        'price_selector' => 'Выбор цены',
        'price_range' => 'Ценовой диапазон:',
        'sort_by' => 'Сортировать по:',
        'for_rent' => 'В аренду',
        'for_sale' => 'На продажу',
        'featured' => 'Избранное',
        'tour_type' => 'Тип тура:',
        'feature_search_type' => 'Поиск по особенностям',
        'tour_type_desc' => '"Если вы не можете лично посетить недвижимость, мы сделаем это за вас и проведем тур по WhatsApp-видео."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Поиск по референс-номеру',
        'search_area' => 'Выберите локацию',
        'search_property_type' => 'Выберите тип недвижимости',
		'search_pricerange' => 'Пожалуйста, выберите диапазон цен',
        'search_pricerange_select' => 'Выберите диапазон цен',
        'search_pricerange_upto' => 'До ',
        'search_pricerange_startsfrom' => 'От ',
        'search_pricerange_to' => ' до ',
        'search_select_dropdown_search' => 'Поиск',
        'search_select_dropdown_clearall' => 'Очистить всё',
        'search_select_dropdown_selectall' => 'Выбрать всё',
        'your_phone' => 'Ваш номер телефона',
        'your_email' => 'Ваш e-mail',
        'your_name' => 'Ваше имя',
        'buyer' => 'Покупатель',
        'agent' => 'Агент',
        'person' => 'Лично',
        'video' => 'Видео',
        'comment' => 'Я заинтересован(а) в ',
    ],
    'buttons' => [
        'search_properties' => 'Поиск недвижимости',
        'search_features' => 'Дополнительные характеристики',
        'submit_request' => 'Отправить запрос',
        'view_more' => 'Подробнее',
        'reset' => 'Сброс',
        'done' => 'Готово',
        'additionalfeatures' => 'Дополнительные характеристики',
        'back_previous' => 'Назад',
        'back_home' => 'На главную',
        'virtual_tour' => 'Виртуальный тур',
        'video_tour' => 'Видео-тур',
        'book_viewing' => 'Записаться на просмотр',
    ],
    'options' => [
        'any' => 'Любой',
        'sort_lowest_price' => 'Цена (сначала ниже)',
        'sort_highest_price' => 'Цена (сначала выше)',
        'sort_location' => 'Локация',
        'sort_most_recent' => 'Сначала новые',
        'sort_oldest' => 'Сначала старые',
        'musthavefeatures1' => 'Совпадает с любой функцией (частично) – Показывать объекты с одной из выбранных функций',
        'musthavefeatures2' => 'Совпадает со всеми функциями (точно) – Показывать только объекты со всеми выбранными функциями',
    ],
    'error' => [
        'prpreferr' => 'Добавьте атрибут ссылки и идентификатор недвижимости для отображения объектов',
        'mls_nosearchresult' => 'Результаты не найдены. Попробуйте еще раз.',
        'mls_sessionexpired' => 'Сессия истекла. Попробуйте еще раз.',
        'mls_no_properties_found' => 'Недвижимость не найдена.',
        'mls_propertdetail_invalid_found' => 'Недопустимая информация об объекте.',
        'mls_propertdetail_not_found' => 'Объект не найден.',
        'mls_propertdetail_no_features' => 'Характеристики не указаны.',
        'mls_propertdetail_no_amenities' => 'Удобства не указаны.',
        'mls_propertdetail_form_name' => 'Пожалуйста, введите ваше имя.',
        'mls_propertdetail_form_email' => 'Пожалуйста, введите ваш e-mail.',
        'mls_propertdetail_form_valid_email' => 'Пожалуйста, введите действительный e-mail.',
        'mls_propertdetail_form_phone_number' => 'Пожалуйста, введите номер телефона.',
        'mls_propertdetail_form_valid_phone_number' => 'Пожалуйста, введите корректный номер телефона.',
        'mls_propertdetail_form_scheduledate' => 'Пожалуйста, выберите дату.',
        'mls_propertdetail_form_submitting' => 'Отправка...',
        'mls_propertdetail_form_submitrequest' => 'Отправить запрос',
        'mls_propertdetail_form_submiterror' => 'Произошла ошибка при отправке формы. Пожалуйста, попробуйте позже.',
        'mls_propertdetail_form_submitsuccess' => 'Спасибо! Ваш запрос был отправлен, письмо отправлено на почту.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Отсутствуют обязательные поля.',
    ],
    'general' => [
        'in' => 'в',
        'month' => 'Месяц',
        'share' => 'Поделиться:',
        'features' => 'Характеристики',
        'description' => 'Описание',
        'additionalfeatures' => 'Дополнительные характеристики',
    ],
    'specification' => [
        'bedrooms' => 'Спальни',
        'bathrooms' => 'Ванные комнаты',
        'built' => 'Площадь застройки',
        'garden' => 'Сад',
        'terrace' => 'Терраса',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Основные характеристики объекта',
        'referenceid' => 'Референс-номер',
        'price' => 'Цена',
        'location' => 'Локация',
        'area' => 'Район',
        'country' => 'Страна',
        'property_type' => 'Тип недвижимости',
        'garbage_fees' => 'Плата за вывоз мусора/год',
        'ibi_fees' => 'Муниципальный налог (IBI)',
    ],
    'prp_map' => [
        'property_location' => 'Расположение объекта (приблизительно)',
        'property_location_descp' => 'Для обеспечения конфиденциальности точный адрес не отображается.',
    ],
],
		'sv' => [
    'labels' => [
        'searchtitle' => 'Hitta ditt drömhem idag!',
        'sales' => 'Till salu',
        'long_rentals' => 'Långtidsuthyrning',
        'short_rentals' => 'Semesterbostäder',
        'new_development' => 'Nyproduktion',
        'area' => 'Område:',
        'no_area' => 'Inga tillgängliga områden',
        'property_type' => 'Bostad:',
        'no_property_type' => 'Inga tillgängliga fastighetstyper',
        'reference_id' => 'Referens ID:',
        'beds' => 'Sovrum:',
        'baths' => 'Badrum:',
        'min_price' => 'Min. pris:',
        'max_price' => 'Max. pris:',
        'price' => 'Pris:',
        'price_selector' => 'Välj pris',
        'price_range' => 'Prisklass:',
        'sort_by' => 'Sortera efter:',
        'for_rent' => 'Att hyra',
        'for_sale' => 'Till salu',
        'featured' => 'Utvalda',
        'tour_type' => 'Typ av visning:',
        'feature_search_type' => 'Sök efter egenskaper',
        'tour_type_desc' => '"Om du inte kan besöka fastigheten själv, gör vi det åt dig via en WhatsApp-video."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Sök med Referens ID',
        'search_area' => 'Välj område',
        'search_property_type' => 'Typ av bostad',
		'search_pricerange' => 'Välj pris',
        'search_pricerange_select' => 'Välj pris',
        'search_pricerange_upto' => 'Upp till ',
        'search_pricerange_startsfrom' => 'Från ',
        'search_pricerange_to' => ' till ',
        'search_select_dropdown_search' => 'Sök',
        'search_select_dropdown_clearall' => 'Rensa alla',
        'search_select_dropdown_selectall' => 'Markera alla',
        'your_phone' => 'Ditt telefonnummer',
        'your_email' => 'Din e-postadress',
        'your_name' => 'Ditt namn',
        'buyer' => 'Köpare',
        'agent' => 'Mäklare',
        'person' => 'Personligen',
        'video' => 'Video',
        'comment' => 'Jag är intresserad av ',
    ],
    'buttons' => [
        'search_properties' => 'Sök bostad',
        'search_features' => 'Fler filter',
        'submit_request' => 'Skicka förfrågan',
        'view_more' => 'Visa mer',
        'reset' => 'Återställ',
        'done' => 'Klar',
        'additionalfeatures' => 'Ytterligare egenskaper',
        'back_previous' => 'Tillbaka',
        'back_home' => 'Hem',
        'virtual_tour' => 'Virtuell rundtur',
        'video_tour' => 'Videovisning',
        'book_viewing' => 'Boka visning',
    ],
    'options' => [
        'any' => 'Antal',
        'sort_lowest_price' => 'Pris (lägst först)',
        'sort_highest_price' => 'Pris (högst först)',
        'sort_location' => 'Plats',
        'sort_most_recent' => 'Senaste först',
        'sort_oldest' => 'Äldsta först',
        'musthavefeatures1' => 'Matcha valfri funktion (delvis) – Visa objekt med någon av de valda funktionerna',
        'musthavefeatures2' => 'Matcha alla funktioner (exakt) – Visa endast objekt med alla valda funktioner',
    ],
    'error' => [
        'prpreferr' => 'Lägg till länkattribut och referens-ID för att visa fastigheter',
        'mls_nosearchresult' => 'Inga resultat hittades. Försök igen.',
        'mls_sessionexpired' => 'Sessionen har gått ut. Försök igen.',
        'mls_no_properties_found' => 'Inga fastigheter hittades.',
        'mls_propertdetail_invalid_found' => 'Ogiltig fastighetsinformation.',
        'mls_propertdetail_not_found' => 'Fastigheten hittades inte.',
        'mls_propertdetail_no_features' => 'Inga egenskaper angivna.',
        'mls_propertdetail_no_amenities' => 'Inga bekvämligheter angivna.',
        'mls_propertdetail_form_name' => 'Ange ditt namn.',
        'mls_propertdetail_form_email' => 'Ange din e-postadress.',
        'mls_propertdetail_form_valid_email' => 'Ange en giltig e-postadress.',
        'mls_propertdetail_form_phone_number' => 'Ange ditt telefonnummer.',
        'mls_propertdetail_form_valid_phone_number' => 'Ange ett giltigt telefonnummer.',
        'mls_propertdetail_form_scheduledate' => 'Välj ett datum.',
        'mls_propertdetail_form_submitting' => 'Skickar...',
        'mls_propertdetail_form_submitrequest' => 'Skicka förfrågan',
        'mls_propertdetail_form_submiterror' => 'Ett fel uppstod vid formulärinlämningen. Försök igen senare.',
        'mls_propertdetail_form_submitsuccess' => 'Tack! Din förfrågan har skickats och ett e-postmeddelande har skickats.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Obligatoriska fält saknas.',
    ],
    'general' => [
        'in' => 'i',
        'month' => 'Månad',
        'share' => 'Dela:',
        'features' => 'Egenskaper',
        'description' => 'Beskrivning',
        'additionalfeatures' => 'Ytterligare egenskaper',
    ],
    'specification' => [
        'bedrooms' => 'Sovrum',
        'bathrooms' => 'Badrum',
        'built' => 'Boyta',
        'garden' => 'Trädgård',
        'terrace' => 'Terrass',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Fastighetens höjdpunkter',
        'referenceid' => 'Referensnummer',
        'price' => 'Pris',
        'location' => 'Plats',
        'area' => 'Område',
        'country' => 'Land',
        'property_type' => 'Fastighetstyp',
        'garbage_fees' => 'Sopavgift/år',
        'ibi_fees' => 'Kommunal skatt (IBI)',
    ],
    'prp_map' => [
        'property_location' => 'Fastighetens plats (ungefärlig)',
        'property_location_descp' => 'För att skydda integriteten visas inte den exakta adressen.',
    ],
],
		'pl' => [
    'labels' => [
        'searchtitle' => 'Znajdź swoje idealne mieszkanie już dziś!',
        'sales' => 'Na sprzedaż',
        'long_rentals' => 'Wynajem długoterminowy',
        'short_rentals' => 'Wynajem krótkoterminowy',
        'new_development' => 'Nowe inwestycje',
        'area' => 'Obszar:',
        'no_area' => 'Brak dostępnych lokalizacji',
        'property_type' => 'Rodzaj nieruchomości:',
        'no_property_type' => 'Brak dostępnych typów nieruchomości',
        'reference_id' => 'Numer referencyjny:',
        'beds' => 'Sypialnie:',
        'baths' => 'Łazienki:',
        'min_price' => 'Min. cena:',
        'max_price' => 'Max. cena:',
        'price' => 'Cena:',
        'price_selector' => 'Wybór ceny',
        'price_range' => 'Zakres cenowy:',
        'sort_by' => 'Sortuj według:',
        'for_rent' => 'Do wynajęcia',
        'for_sale' => 'Na sprzedaż',
        'featured' => 'Wyróżnione',
        'tour_type' => 'Rodzaj wycieczki:',
        'feature_search_type' => 'Wyszukiwanie cech',
        'tour_type_desc' => '"Jeśli nie możesz odwiedzić nieruchomości osobiście, zrobimy to za Ciebie, korzystając z wideorozmowy na WhatsApp."',
    ],
    'placeholders' => [
        'search_reference_id' => 'Wyszukaj według numeru referencyjnego',
        'search_area' => 'Wybierz lokalizację',
        'search_property_type' => 'Wybierz typ nieruchomości',
		'search_pricerange' => 'Proszę wybrać przedział cenowy',
        'search_pricerange_select' => 'Wybierz przedział cenowy',
        'search_pricerange_upto' => 'Do ',
        'search_pricerange_startsfrom' => 'Od ',
        'search_pricerange_to' => ' do ',
        'search_select_dropdown_search' => 'Szukaj',
        'search_select_dropdown_clearall' => 'Wyczyść wszystko',
        'search_select_dropdown_selectall' => 'Zaznacz wszystko',
        'your_phone' => 'Twój numer telefonu',
        'your_email' => 'Twój adres e-mail',
        'your_name' => 'Twoje imię',
        'buyer' => 'Kupujący',
        'agent' => 'Agent',
        'person' => 'Osobiście',
        'video' => 'Wideo',
        'comment' => 'Jestem zainteresowany ',
    ],
    'buttons' => [
        'search_properties' => 'Wyszukaj nieruchomości',
        'search_features' => 'Więcej filtrów',
        'submit_request' => 'Złóż zapytanie',
        'view_more' => 'Zobacz więcej',
        'reset' => 'Zresetuj',
        'done' => 'Gotowe',
        'additionalfeatures' => 'Dodatkowe cechy',
        'back_previous' => 'Wróć',
        'back_home' => 'Powrót do strony głównej',
        'virtual_tour' => 'Wirtualna wycieczka',
        'video_tour' => 'Wideo tour',
        'book_viewing' => 'Zarezerwuj wizytę',
    ],
    'options' => [
        'any' => 'Dowolny',
        'sort_lowest_price' => 'Cena (najniższa najpierw)',
        'sort_highest_price' => 'Cena (najwyższa najpierw)',
        'sort_location' => 'Lokalizacja',
        'sort_most_recent' => 'Ostatnio dodane',
        'sort_oldest' => 'Najstarsze najpierw',
        'musthavefeatures1' => 'Pasuje do dowolnej cechy (częściowo) – Pokaż nieruchomości z jedną z wybranych cech',
        'musthavefeatures2' => 'Pasuje do wszystkich cech (dokładnie) – Pokaż tylko nieruchomości z wszystkimi wybranymi cechami',
    ],
    'error' => [
        'prpreferr' => 'Dodaj atrybut referencyjny i ID nieruchomości, aby wyświetlić wyniki',
        'mls_nosearchresult' => 'Brak wyników. Spróbuj ponownie.',
        'mls_sessionexpired' => 'Sesja wygasła. Spróbuj ponownie.',
        'mls_no_properties_found' => 'Brak nieruchomości.',
        'mls_propertdetail_invalid_found' => 'Nieprawidłowe informacje o nieruchomości.',
        'mls_propertdetail_not_found' => 'Nieruchomość nie została znaleziona.',
        'mls_propertdetail_no_features' => 'Brak dostępnych cech.',
        'mls_propertdetail_no_amenities' => 'Brak dostępnych udogodnień.',
        'mls_propertdetail_form_name' => 'Wpisz swoje imię.',
        'mls_propertdetail_form_email' => 'Wpisz swój adres e-mail.',
        'mls_propertdetail_form_valid_email' => 'Wpisz poprawny adres e-mail.',
        'mls_propertdetail_form_phone_number' => 'Wpisz swój numer telefonu.',
        'mls_propertdetail_form_valid_phone_number' => 'Wpisz poprawny numer telefonu.',
        'mls_propertdetail_form_scheduledate' => 'Wybierz datę.',
        'mls_propertdetail_form_submitting' => 'Wysyłanie...',
        'mls_propertdetail_form_submitrequest' => 'Złóż zapytanie',
        'mls_propertdetail_form_submiterror' => 'Wystąpił problem z przesyłaniem formularza. Spróbuj ponownie.',
        'mls_propertdetail_form_submitsuccess' => 'Dziękujemy! Twoje zapytanie zostało wysłane, a e-mail został wysłany.',
        'mls_propertdetail_form_submitrequiredmissing' => 'Brak wymaganych pól.',
    ],
    'general' => [
        'in' => 'w',
        'month' => 'Miesiąc',
        'share' => 'Podziel się:',
        'features' => 'Cechy',
        'description' => 'Opis',
        'additionalfeatures' => 'Dodatkowe cechy',
    ],
    'specification' => [
        'bedrooms' => 'Sypialnie',
        'bathrooms' => 'Łazienki',
        'built' => 'Powierzchnia mieszkania',
        'garden' => 'Ogród',
        'terrace' => 'Taras',
    ],
    'prp_highlights' => [
        'property_highlights' => 'Wyróżnione cechy nieruchomości',
        'referenceid' => 'Numer referencyjny',
        'price' => 'Cena',
        'location' => 'Lokalizacja',
        'area' => 'Obszar',
        'country' => 'Kraj',
        'property_type' => 'Typ nieruchomości',
        'garbage_fees' => 'Opłata za śmieci/rok',
        'ibi_fees' => 'Podatek od nieruchomości (IBI)',
    ],
    'prp_map' => [
        'property_location' => 'Lokalizacja nieruchomości (przybliżona)',
        'property_location_descp' => 'Dla zachowania prywatności mapa pokazuje przybliżoną lokalizację nieruchomości. Skontaktuj się z nami po dokładne szczegóły lub w celu umówienia wizyty.',
    ],
],
		




];
}

/*function mls_plugin_translate($key) {
    $current_language = mls_plugin_get_current_language();
    $translations = mls_plugin_get_translations();

    if (isset($translations[$current_language][$key])) {
        return $translations[$current_language][$key];
    }

    // Fallback to English if key not found in selected language
    return $translations['en'][$key] ?? $key;
}*/

function mls_plugin_translate($key, $nested_key) {
    $current_language = mls_plugin_get_current_language();
    $translations = mls_plugin_get_translations();

    // Check if nested key exists in the current language
    if (isset($translations[$current_language][$key][$nested_key])) {
        return $translations[$current_language][$key][$nested_key];
    }

    // Fallback to English if nested key doesn't exist in the current language
    return $translations['en'][$key][$nested_key] ?? '';
}